1
1
Tests run  6
Errors  [(<CheckSuite.CheckSuite testMethod=test_init_1>, 'Traceback (most recent call last):\n  File "./test/CheckSuite.py", line 68, in test_init_1\n    expect = str(TypeMismatchInStatement(ast))\nNameError: name \'ast\' is not defined\n'), (<CheckSuite.CheckSuite testMethod=test_init_3>, 'Traceback (most recent call last):\n  File "./test/CheckSuite.py", line 88, in test_init_3\n    expect = str(TypeMismatchInStatement(ast))\nNameError: name \'ast\' is not defined\n'), (<CheckSuite.CheckSuite testMethod=test_init_4>, 'Traceback (most recent call last):\n  File "./test/CheckSuite.py", line 98, in test_init_4\n    expect = str(TypeMismatchInStatement(ast))\nNameError: name \'ast\' is not defined\n'), (<CheckSuite.CheckSuite testMethod=test_init_5>, 'Traceback (most recent call last):\n  File "./test/CheckSuite.py", line 108, in test_init_5\n    expect = str(TypeMismatchInStatement(ast))\nNameError: name \'ast\' is not defined\n')]
[]
Test output
 E.EEE.
======================================================================
ERROR: test_init_1 (CheckSuite.CheckSuite)
Simple program: main
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 68, in test_init_1
    expect = str(TypeMismatchInStatement(ast))
NameError: name 'ast' is not defined

======================================================================
ERROR: test_init_3 (CheckSuite.CheckSuite)
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 88, in test_init_3
    expect = str(TypeMismatchInStatement(ast))
NameError: name 'ast' is not defined

======================================================================
ERROR: test_init_4 (CheckSuite.CheckSuite)
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 98, in test_init_4
    expect = str(TypeMismatchInStatement(ast))
NameError: name 'ast' is not defined

======================================================================
ERROR: test_init_5 (CheckSuite.CheckSuite)
Not same dimen
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/CheckSuite.py", line 108, in test_init_5
    expect = str(TypeMismatchInStatement(ast))
NameError: name 'ast' is not defined

----------------------------------------------------------------------
Ran 6 tests in 0.044s

FAILED (errors=4)

